#!/bin/bash
#----------------
# Testing varnish
#----------------
set -e
DAEMON=varnishd

if pidof -x $DAEMON > /dev/null; then
    echo "OK"
else
    echo "ERROR: ${DAEMON} IS NOT RUNNING"
    exit 1
fi
