#!/bin/bash
#--------------------
# Testing varnishncsa
#--------------------
set -e

# modify varnishncsa file
CONFIG_FILE=/etc/default/varnishncsa
DAEMON=varnishncsa
sed -i -e "s/# VARNISHNCSA_ENABLED=1/VARNISHNCSA_ENABLED=1/g" $CONFIG_FILE
/etc/init.d/${DAEMON} restart

if pidof -x $DAEMON > /dev/null; then
    echo "OK"
else
    echo "ERROR: ${DAEMON} IS NOT RUNNING"
    exit 1
fi
